name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Heyy Contributor! Thank you for creating an issue in this repository! We'll check it out as soon as possible."
        pr-message: "Heyy Contributor! Thank you for creating an pull request in this repository! We'll reivew it out as soon as possible."
